[package]
name = "faasm-wrapper"
version = "0.1.0"
authors = ["Mayeul Fournial <mfournial@outlook.com>"]
edition = "2018"
license = "Apache2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faasm-sys = { path = "../faasm-sys" }
